imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        algolia_app_id: '%algolia.application_id%'
        algolia_search_key: '%algolia.search_key%'
algolia:
    catch_log_exceptions: true

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "welkom@ervarentrainers.nl"
        sender_name: "Ervaren Trainers"
    registration:
        confirmation:
            enabled: true
        form:
            type: \AppBundle\Form\RegistrationType

easy_admin:
    design:
        form_theme: ['horizontal', 'form/admin_vich_image_widget.html.twig']
    entities:
        User:
            class: AppBundle\Entity\User
            list:
                fields:
                    - firstName
                    - lastName
                    - email
                    - createdAt
                    - updatedAt
            form:
                fields:
                    - firstName
                    - lastName
                    - { property: 'ervaring', type: 'text', type_options: { required: false } }
                    - { property: 'typeTrainer', type: 'text', type_options: { required: false } }
                    - { property: 'motto', type: 'text', type_options: { required: false } }
                    - { property: 'geboorteDatum', type: 'birthday' }
                    - property: 'geslacht'
                      type: 'choice'
                      type_options:
                          choices:
                              male: !php/const:\AppBundle\Entity\User::GENDER_MALE
                              female: !php/const:\AppBundle\Entity\User::GENDER_FEMALE
                    - vog
                    - { property: 'verified', type: 'checkbox' }
                    - email
                    - phoneNumber
                    - street
                    - streetNumber
                    - zipcode
                    - city
                    - { property: 'description', type: 'ckeditor', type_options: { required: false } }
                    - enabled
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', required: false, type_options: { multiple: true, expanded: true, choices: { 'Admin': 'ROLE_ADMIN' } } }
                    - { property: 'avatarFile', type: 'vich_image', type_options: {imagine_pattern: 'basic_thumbnail'} }
                    - { property: 'coverPhotoFile', type: 'vich_image', type_options: {imagine_pattern: 'basic_thumbnail'} }
                    - property: 'education'
                      type: '\Symfony\Component\Form\Extension\Core\Type\CollectionType'
                      type_options:
                        entry_type: '\AppBundle\Form\EducationType'
                        allow_add: true
                        allow_delete: true
                    - property: 'usps'
                      type: '\Symfony\Component\Form\Extension\Core\Type\CollectionType'
                      type_options:
                        entry_type: '\Symfony\Component\Form\Extension\Core\Type\TextType'
                        allow_add: true
                        allow_delete: true
        Training:
            class: AppBundle\Entity\Training
            form:
                fields:
                - title
                - description
                - tags
                - boost
                - property: 'photoFile'
                  type: 'vich_image'
                  type_options: {imagine_pattern: 'basic_thumbnail'}
                - property: 'prices'
                  type: '\Symfony\Component\Form\Extension\Core\Type\CollectionType'
                  type_options:
                    entry_type: '\AppBundle\Form\TrainingPriceType'
                    allow_add: true
                    allow_delete: true
                    by_reference: false
                - property: 'user'
                  type: 'entity'
                  type_options:
                    class: '\AppBundle\Entity\User'
                    choice_label: 'email'
vich_uploader:
    db_driver: orm
    mappings:
        general_image:
            uri_prefix:         /upload/image
            upload_destination: '%kernel.root_dir%/../var/upload/image'
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     true

liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root: '%kernel.root_dir%/../var/'
    filter_sets:
        cache: ~
        basic_thumbnail:
            quality: 100
            filters:
                thumbnail: { size: [45,45], mode: inset }
        avatar_profile:
            quality: 100
            filters:
                thumbnail: { size: [390,390], mode: outbound }
        avatar_overview:
            quality: 100
            filters:
                thumbnail: { size: [293,293], mode: outbound }

        cover_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [1920,300], mode: inset }
        cover_full:
            quality: 75
            filters:
                thumbnail: { size: [1903,800], mode: inset }
        optimize_only:
            quality: 75

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
